#!/bin/bash
pd=/Applications/Pd-0.48-1.app/Contents/Resources/bin/pd
pd32=/Applications/Pd-0.48-1-i386.app/Contents/Resources/bin/pd
PORTNUM=5012
TOTDUR=480000
#TOTDUR=30000


pd32send="\
\
\
;netsend connect localhost $PORTNUM\
;spigot-rec 1\
;gemwin 0, destroy, dimen 600 600, frame 30, create, 1\
;rec 1\
;start bang\
;stop-after $TOTDUR\
\
\
\
"


pdsend="\
\
\
;netreceive listen $PORTNUM\
;rec-id 1\
\
\
"
#-noverbose -nogui 

$pd -send $pdsend -open ./bin/main.pd & 

sleep 1

$pd32 -send $pd32send -open ./bin/main_gem.pd
