#!/bin/bash
#
#
#

#####################################################################
#
#	Variables
#
######################################################################


# AUDIO PATCH IP address (localhost or 127.0.0.1 if same computer)
address=127.0.0.1
# Port number for the inter-patch TCP flow
portnum=5012



# Adjust Gem window dimension
dimen="1920 1080"
# Fullscreen 0, 1 in current display, 2 in separate display
fullscreen=2
# Frames per second
frame=60
# FSAA
fsaa=4

# Allow recording
rec=0
# Set recording id
rec_id=1


# Time out to stop the music (20 minutes default)
stop_after=1200000



#####################################################################
#
#	Pd Paths:
#
######################################################################


pd=/Applications/Pd-0.48-1.app/Contents/Resources/bin/pd
pd32=/Applications/Pd-0.48-1-i386.app/Contents/Resources/bin/pd



#####################################################################
#
#	pdsend messages
#
######################################################################


pd32send="\
\
\
;netsend connect $address $portnum\
;spigot-rec $rec\
;gemwin \
0, destroy, \
dimen $dimen, \
frame $frame,\
fullscreen $fullscreen,
FSAA $fsaa,\
create, 1\
;rec $rec\
;start bang\
;stop-after $stop_after\
\
\
\
"

pdsend="\
\
\
;netreceive listen $portnum\
;rec-id $rec_id\
\
\
"


#####################################################################
#
#	Check arguments and run the patches
#
######################################################################

# run_audio_patch="$pd -send "\"$pdsend\"" -open ./bin/main.pd"
# run_video_patch="$pd32 -send "\"$pd32send\"" -open ./bin/main_gem.pd"

#-noverbose -nogui 


AUDIO=0
VIDEO=0
AV=1

if [[ $1 ]]
then
	if [[ $1 == "video" ]] 
	then
		echo "video patch"
		VIDEO=1
		AUDIO=0
		AV=0
	else
		if [[ $1 == "audio" ]]
		then
			echo "audio patch"
			AUDIO=1
			VIDEO=0
			AV=0
		else
			echo "cant understand: $1\
			usage: ./run [video,audio] (no argument runs both)"
			exit
		fi
	fi
else
	echo "running both audio and video patch"
	AV=1
	AUDIO=0
	VIDEO=0
fi

if [[ $AUDIO == 1 ]]
then
	# echo "$run_audio_patch"
	$pd -send "$pdsend" -open ./bin/main.pd
	exit 0
else
	if [[ $VIDEO == 1 ]]
	then
		# echo "$run_video_patch"
		$pd32 -nogui -send "$pd32send" -open ./bin/main_gem.pd
		exit 0
	fi
fi

if [[ $AV == 1 ]]
then
	# echo "$run_audio_patch"
	$pd -send "$pdsend" -open ./bin/main.pd &
	sleep 1
	# echo "$run_video_patch"
	$pd32 -nogui -send "$pd32send" -open ./bin/main_gem.pd
	exit
fi
